language: python
python:
  - "2.6"
  - "2.7"

# command to install dependencies
before_install: 
    - pip install -r dev-requirements.txt

before_script:
    - psql -c 'create database hiero_test;' -U postgres

install: 
    - python setup.py install

# command to run tests
script: 
    - python setup.py test
